### ISSUE TITLE
Self-control timer at 0.00.00

### ISSUE THREAD

**Issue by rickogorman** [SelfControlApp/selfcontrol#103]
I updated self-control yesterday and it doesn't run correctly. It's window shows 0.00.00 and it seems to indicate that the block is over. But if I try to edit the blacklist it says I can't because there is a block in place. I rolled back to version 1.5 but the problem now remains, even though it wasn't there before the 1.5.1 update. I'll try to see what it does when it is out of the block.

**Comment by nelsogom** [comment]
Hi, I had the same problem twice. I found the fix the first time after trying for months on and off to find the solution. Then, it happened again and I couldn't remember what I did, but I knew it has something to do with Preferences. The problem is that if you search your Library for "Self" you are not going to find anything to self-control or anything like that. OK, to make a long story short here is the solution (I'm currently on MacOS Sierra 10.12.6):

Make sure Self-Control is not running
Go to your Library (hold option key and click on Go menu and you should see Library listed)
Open your Preferences folder
Search for "org.eyebeam.SelfControl.plist" and then trash the file
Restart your computer
Open Self-Control and you will be ready to go

Unfortunately, you will need to enter the blocked sites one more time. I had many, but then I remember the SelfControl-Killer.log and when I opened it in Console the list was there. I had to copy and paste to add the sites but that took a minute or two.

Hope this works for the next person looking for the solution.
