### ISSUE TITLE
Support minimizing + menu bar icon

### ISSUE THREAD

**Issue by jamesdh** [SelfControlApp/selfcontrol#266]
Rather than having to cmd-tab to the Self Control app to see how much time is remaining or to start it, it would be nice if it were just available in the OS X menu bar.

The best feature about this is it could be done such that it always shows a countdown in the menu bar so a simple glance will tell us how much time remains. It also gets it out of our Cmd-Tab list of apps (for those of us switching apps frequently). 

Many users (especially developers) minimize their Dock just to get added real estate. Only having the icon in the dock sucks for those users.

**Comment by cstigler** [comment]
@jamesdh sounds awesome. build it!

**Comment by jamesdh** [comment]
What? You mean I'm supposed to contribute to an open source project? What sort of nonsense is that?! :shipit: :neckbeard:

**Comment by yusen1124** [comment]
@jamesdh It's great,but it will be wonderful if the time can be longer even be forever.To be honest,I really hope so.

**Comment by maxigimenez** [comment]
Any idea of create a menu bar version?

**Comment by jamesdh** [comment]
App appears to no longer be maintained. Closing.

**Comment by kn107** [comment]
Does this mean the app is not supported anymore?

**Comment by cstigler** [comment]
@khangnh107 Good news, it's no less supported than it has been since 2009 when I launched it! Bad news, it's never been supported :p

I'll keep updating it when I have time, which is occasionally. In practice, it seems like every few years I work up the energy to do another lil work sprint on it, and then leave it be for a while. It's free software - ya get what ya pay for

**Comment by kn107** [comment]
Nice. I was just worried because I have no idea how it works exactly under the hood. Like, what if it suddenly just blocks everything and then forgets to unblock it back, and then I have no way of reversing the changes? Would you say that it's something that can happen 🥲?

**Comment by cstigler** [comment]
> Nice. I was just worried because I have no idea how it works exactly under the hood. Like, what if it suddenly just blocks everything and then forgets to unblock it back, and then I have no way of reversing the changes? Would you say that it's something that can happen 🥲?

The main issue people have goes like this:

1. They use our sort-of-hidden tweaking parameters to make SelfControl block for much longer than the default 24 hours, e.g. several years

2. They start an extremely long block without thoroughly testing it

3. At some point after starting the block, they realize that it accidentally includes a site they didn't mean to block. e.g. maybe they tried to block Google Image Search but didn't realize it would block Google Docs also

4. They panic because they have now blocked something essential for years

Just don't set long blocks, or if you do test them very, very, very thoroughly. That's the best way to avoid issues! (and if you do screw things up, you can email me and I'll sort you out, but it may not be as fast as you want)

**Comment by kn107** [comment]
Thank you! That really cleared things up for me 😄
