### ISSUE TITLE
Killer?

### ISSUE THREAD

**Issue by coreycondardo** [SelfControlApp/selfcontrol#303]
Is there a link to the killer? I was using this for development purposes (trying to block Facebook to recreate a customer issue) and accidentally set the blocker to 24 hours. I need to stop all SelfControl blocking, if possible.

Thanks!
Corey

**Comment by madebyherzblut** [comment]
Have you tried https://github.com/SelfControlApp/selfcontrol/issues/299?

**Comment by slambert** [comment]
Not positive it works on the newer versions...

**Comment by cstigler** [comment]
There is currently no Killer app for the new versions - we bundle the functionality into the app now so that people are automatically presented with the option to remove their own block when things go wrong. Which is much nicer for us - no more sending it out to users!

(seconded @madebyherzblut on trying the workaround in #299 - it isn't that hard to get around if you know how ;)
