### ISSUE TITLE
Self Control doesn't work at all

### ISSUE THREAD

**Issue by missjargo** [SelfControlApp/selfcontrol#363]
Self Control has been working fine for me since 2013, but last week I noticed one occasion that I could still access sites during block mode. That block timed out and the next one worked fine, but the same thing was repeated the a few days later.

Today, after doing the lasted OS update - to 10.11.15 - it doesn't block any sites AT ALL!

Please help.

**Comment by c0ppo** [comment]
Same thing here. OS X 10.11.6, and selfcontrol can't block anything :(

**Comment by mohankv** [comment]
I donwloaded the latest version, it is not blocking anything.

**Comment by digital-discuss** [comment]
Same here, but is limited to Firefox and existing black list.

**Comment by boithisappsucks** [comment]
This is the worst possible app to download. Doesn't even work properly. Whoever made this app is just messed up. No offence.

**Comment by digital-discuss** [comment]
@boithisappsucks , you did notice the source code, right? This app used to work great.

**Comment by digital-discuss** [comment]
As you can read in my [previous report](https://github.com/SelfControlApp/selfcontrol/issues/547) I discovered that the current Firefox 66 resolved my issues with SC 2.2.2. I suspect that the Proxy settings for some reason may have bypassed or disregarded the mechanism SC makes use of.

If this is true, then it's of vital importance which browser you're using and which version of it, when SC isn't working for you.

**Comment by slambert** [comment]
Did you read the instructions? No offense.

**Comment by cstigler** [comment]
😛 lol thanks for the constructive criticism?

**Comment by cstigler** [comment]
for all the well-intentioned people in this thread: I'm sorry it's not working properly for you! Unfortunately, this issue is unlikely to lead to a resolution. It's nearly impossible to debug something as general as "it's not working", not to mention that I have barely any time to look at these anyway.

If the app isn't working for you, start by considering if you might using a proxy, firewall, or VPN (very common with work/school computers in particular). That's probably the most common cause of it not working. Then try clearing your browser cache, then quitting your browser and restarting - that's another big one.

If it's still not working and you're hoping for a fix, you can open a GitHub Issue with more details. For example:
- macOS version
- SelfControl version
- special circumstances on the computer (proxy/firewall/VPN/etc)
- browser type/version
- have you tried clearing caches and restarting the browser?
- has it ever worked for you, or when did it stop working?
- what exactly happens when you start a block?
- what happens when you try to access the websites?
- are some things blocked, or sometimes? what patterns do you see?

I _still_ won't likely be able to respond to all of these, but at least you'd be contributing your experiences towards an eventual fix!

otherwise - closing this thread
