### ISSUE TITLE
Piece of Garbage

### ISSUE THREAD

**Issue by chinanderm** [SelfControlApp/selfcontrol#374]
What a piece of crap application. Sure, it does what is says it does, but the amount of garbage it spreads on your system is unreal. To stop a timer and remove the app is a process as you have to find all the **** processes and files it liters all over your system.

**Comment by cstigler** [comment]
Thanks for the helpful feedback.

**Comment by jbregar** [comment]
It could have probably been phrased differently but there _is_ helpful feedback in this issue.

While I understand why the decision was made, perhaps it's a bad idea to make your app so pervasive that removing it or stopping the process is such an involved process.

If I (as a user) accidentally set the timer for a long time and start it, it shouldn't take a trip to the Apple Store and a reinstall of the OS to undo that mistake. That's a terrible user experience.

**Comment by cstigler** [comment]
@jbregar That's a totally valid viewpoint, but that's not what SelfControl does. This is an application that's made to be very difficult to remove -- it's a listed feature that some people are very happy about. And we still have plenty of users complaining that it's too easy to remove!

There are other web-blocking apps; we're certainly not the only one anymore. Some of them are one-click to start and stop the block, and that works great for some people. That's not how SelfControl works, and I don't expect that to change in the near future.

**Comment by jbregar** [comment]
Fair enough. Then the problem is probably one of perception and you need to address it elsewhere. 

In viewing your web site for SelfControl, it really isn't made clear what's going on and how pervasive and hard to remove the app really is. You should probably make that clear both when the user decides to download SelfControl and in the Quick Start window that pops up the first time it opens. In the absence of a warning, users are going to assume that this app works like all the others and  have certain expectations based on that. Relying on your FAQ to crutch this assumption isn't really enough.

Second, the app should probably warn about its pervasiveness you again the first time (or times) you set up a timer. It should also probably warn you one more time when you set a timer for some threshold of time that would be considered "long"... so people don't inadvertently set overly long timers. Something like "Are you sure you want to shut off your internet access for 24 hours? It's really hard to un-do this action."

There should probably also be some way to cancel it regardless... it's ok to say "wait it out" when your max time period is 20 minutes. It's not really ok when that time period is 24 hours. Maybe have a way to cancel if the time period is set over an hour (just a thought). A lot can change in a user's day in an hour or two and they may need access to a site they didn't think they would. 

All of this is doubly-bad when you admit that you'll sometimes inadvertently block sites that are hosted on the same server as blocked sites. What if JoesGames.com is on the same server as CSSHelp.org? No offense, but that's a pretty bad bug.

To bring this into something you have experience with (considering your Medium post) your app as it currently sits is like a shower that asks you what temperature water you want and for how long, then locks you in the shower for that entire duration. Better hope you didn't over- or under-estimate your temp before you turn it on.

**Comment by cstigler** [comment]
I won't have time to respond to this in detail, so I'll just say 1) I appreciate the thought you're putting into this, 2) I agree with some of this and disagree with some, and 3) PRs that improve communication are very welcome =)

**Comment by slambert** [comment]
@jbregar I'll also add, the icon is the same one that you'd find on a poison bottle for a reason.

As a friendly reminder, we're not a company and this isn't customer service. This is an open source project, not a commercial product. If you don't like how it works, we've _given away the code for free_. You are free to change it (or you can hire someone) to work _however you think it should_. So, if you feel strongly, do that.

**Comment by jbregar** [comment]
Not sure too many users will make the poison bottle connection. 

I couldn't care less about how it works, I don't use the software (and likely never will after reading the FAQ). I don't even remember how I got here initially. I just wanted to point out that there _is_ useful feedback in the initial issue, however abrasively it's worded. Obviously the original submitter didn't get your poison bottle connection. 

My point was just that apps like this that can do real damage to a user's experience with their computer really need to be diligent about warning their users about what's going to happen. You can't rely on cutesy icons and a FAQ to get the message across.

I've provided a few alternative ideas that might make it a little harder for a user to hang himself with your app and end up pissed off like the original submitter. They're offered in good faith. You're free to take them and do what you please up to and including telling me to pound sand (which it appears is your response).

**Comment by slambert** [comment]
@jbregar Ah, I thought you and the original poster were the same. Thanks for taking the time to clarify, you do have some good points here. I've been surprised over the years at how many people just don't read, but there's some ideas here we can use. Thanks.
