### ISSUE TITLE
SelfControl blacklist does not expire once control time completed macOS Sierra

### ISSUE THREAD

**Issue by shaun10** [SelfControlApp/selfcontrol#396]
Time completed but blacklist has persisted. After restarting, or removing app, blacklist still persists. Anyone know way to manually disable?

**Comment by cstigler** [comment]
Open app, start a short block if it thinks it's already done (if it's showing the Start button instead of the timer). When it hits 00:00, if it stays blocked, wait ten seconds as it shows 00:00, then a button labeled "Stuck? Stop block manually." will replace the "Add to Blocklist" button." Click it and remove your block manually! You may need to restart your computer after removing the block manually to get it working right.

**Comment by shaun10** [comment]
It doesn't think it's done. 
![screen shot 2016-11-12 at 7 00 06 am](https://cloud.githubusercontent.com/assets/7233643/20237946/afcab6ca-a8a5-11e6-8a6f-256e04044197.png)
