### ISSUE TITLE
Timer stuck at 00:00

### ISSUE THREAD

**Issue by slambert** [SelfControlApp/selfcontrol#4]
THIS IS A KNOWN ISSUE - see the FAQ in the wiki for a fix
https://github.com/slambert/selfcontrol/wiki/FAQ

Ticket migrated from here (check link for history)
http://dev.eyebeam.org/projects/selfcontrol-app/ticket/340

**Comment by nelsogom** [comment]
Hi, I had the same problem twice. I found the fix the first time after trying for months on and off to find the solution. Then, it happened again and I couldn't remember what I did, but I knew it has something to do with Preferences. The problem is that if you search your Library for "Self" you are not going to find anything to self-control or anything like that. OK, to make a long story short here is the solution:

1. Make sure Self-Control is not running
2. Go to your Library (hold option key and click on Go menu and you should see Library listed)
3. Open your Preferences folder
4. Search for "org.eyebeam.SelfControl.plist" and then trash the file
5. Restart your computer
6. Open Self-Control and you will be ready to go (if you see the 00:00:00 again click on unblock manually and that should do it).

Unfortunately, you will need to enter the blocked sites one more time. I had many, but then I remember the SelfControl-Killer.log in the Documents folder and when I opened it in Console the list was there. I had to copy and paste to add the sites but that took a minute . 

Hope this works for the next person looking for the solution.

**Comment by cstigler** [comment]
Just to clarify, the button to stop the block manually will show up 10 seconds after the block was supposed to stop automatically in all modern versions of SelfControl. You don't need to delete the plist file to make that button show up, and I wouldn't recommend it.

If the timer is stuck at 00:00:00, the best action is to wait 10 seconds for the "stop block manually" button to appear, and then use it to stop the block.

**Comment by sarweshshah** [comment]
@cstigler already clicked in 'stop block manually'. No avail. Please help!!

**Comment by cstigler** [comment]
@sarweshshah have you tried restarting your computer after removing the block?

If so, please email that `SelfControl-Killer` log file to me at charlie+sc4@charliestigler.com, along with your SelfControl version, OS version, and any other relevant info.

**Comment by sarweshshah** [comment]
I download an older version of Self-Control and restarted the timer. It ended alright. And then I uninstalled the application!
