### ISSUE TITLE
Can't block telegram web

### ISSUE THREAD

**Issue by harveycabaguio** [SelfControlApp/selfcontrol#409]
I add https://web.telegram.org/ to my blacklist, but I'm still able to access the site.

**Comment by colasbd** [comment]
Have you tried adding only `telegram.org`?

**Comment by GandalfSaxe** [comment]
I have the same issue.

tried:

telegram.org
https://web.telegram.org/
https://web.telegram.org/#/im

**Comment by Armingus** [comment]
Same here. Tried EVERYTHING! :(

**Comment by cstigler** [comment]
Hi all, thanks for the feedback. Since this kind of issue ("this website isn't blocked even though it should be") is very common and it's been nearly impossible for me to keep up with our GItHub Issues, I started a [new issue](https://github.com/SelfControlApp/selfcontrol/issues/680) to consolidate all of these kinds of problems in one place.

**I've added this on your behalf to [that meta-issue](https://github.com/SelfControlApp/selfcontrol/issues/680).** Hopefully this will help me triage and fix more problems in the future.

Thanks for the help and hope things have cleared up since these comments were left.
