### ISSUE TITLE
Changing date and time overrides self control blocking timer

### ISSUE THREAD

**Issue by iren98765** [SelfControlApp/selfcontrol#423]
Hi is it possible to create a timer for this application rather than have it rely on the computer's time and date? Currently, if you change the computer's time and date, it disables self control functionality.

**Comment by HisBoilingPoint** [comment]
(technacy it doesn't override it, it just is doing what is programed to do with the information it has been given, you have just manipulated/changed that information) To answer your question, yes you could add it's own timer instead of the computers one but someone would have to be bothered enuff to make it but you then come to the problem of when you close the app or restart your computer and the timer won't be able to run through that. A hybrid system that uses its own timer, as well as the computers, would be better but you could still close the app/restart and change the time on the computer and there is no way of preventing that. But by that stage, if you're bothered enuff to do all that then you might as well, rather than bypassing all that, just don't put it on in the first place :)

**Comment by owencolby** [comment]
Could it use a internet based timer that cannot be changed to fix this?

**Comment by slambert** [comment]
Duplicate: https://github.com/SelfControlApp/selfcontrol/issues/28
