### ISSUE TITLE
Is there some kind of explanation how this app works?

### ISSUE THREAD

**Issue by E3V3A** [SelfControlApp/selfcontrol#495]
This seem to be an interesting app to help block certain content from kids.
But kids are very savvy these days, so...

* Is there some kind of explanation how this app works under the hood?
  (I did see it does something to the hosts file, but that if you manipulate it, it will get restored. 
How is that done?)
* If you remove the app, how does it persists? (Anyone else would regard this as malware, so at least tell us how it works.)

Thanks in advance.

**Comment by cstigler** [comment]
Hi @E3V3A , we don't talk much about this on the FAQ/site because a lot of people prefer less info to help them work around it.

SelfControl blocks via two methods: 1) modifying the hosts file, and 2) modifying the system's `pf` firewall. It also has an agent that runs regularly to modify these methods and fix the block if anybody has tampered with it.

There's no real trick to it persisting if it's removed - in macOS removing an app doesn't undo all of the changes it has made (to `hosts`, `pf`, or the agent), so it stays by default.

**Comment by E3V3A** [comment]
@cstigler Super answer. Thank you. Will definitely try this.
