### ISSUE TITLE
I STILL CAN ACCESS THE WEBSITE I BLOCKED 

### ISSUE THREAD

**Issue by usercora** [SelfControlApp/selfcontrol#498]
Hello. 
Firstly, I really appreciate you for providing this useful app. 
This helps me enhance my productivity by the way. 

By the way , I am confronting huge crisis now... this app cannot block the site anymore... omg... 

It worked well until yesterday , but today after I adjust the length to 1month through application utility and terminal, the app is not working. 
More specifically, the timer only works , but still it can NOT control me accessing black list websites.
Actually I succeed on brooding the time limit to 1->30 day. But the app is not blocking the site as it did before .  

I've tried many things, such as that 3 procedures you introduced on FAQ. 
However... nothing changed and I'm kinda sucked... 

help me please. SOS 

user annayun11

**Comment by usercora** [comment]
please help me

**Comment by cstigler** [comment]
Hi @usercora, I'm sorry you're having issues with the app. Since this app is maintained on a volunteer basis, most issues can't get personal attention on a timely basis. I would advise trying some basic troubleshooting techniques on your own:

1. Restart the computer
2. Try waiting for your current block to end, uninstalling SelfControl, and starting another block.

I hope you're able to find a resolution to your issue.
