### ISSUE TITLE
When running, Self Control blocks website not on my Blacklist

### ISSUE THREAD

**Issue by puntnomads** [SelfControlApp/selfcontrol#555]
Hello,
I love this application and it has been enormously helpful to me. However, whenever it is running, it blocks github.com, which I unfortunately need for work. The sites I typically block are openload.co, streamango, etc. Perhaps there is some connection between those sites that forces github.com to be blocked? Either way, I can't access it while Self Control is running. I have tried to find the domain that is hosted on the same server as github.com but was not able to find any connections when i checked where the domains are hosted. How can I find out if 2 domains share the same server or rely on the same backend service?

Thanks and Best,
puntnomads

**Comment by cstigler** [comment]
Hi @puntnomads, unfortunately I can't say the answer for this one. But since it sounds like you're a developer, I can suggest some starting steps to understand the problem:

1) Start a SelfControl block with your usual blocklist.

2) Run `cat /etc/hosts` to see the list of domain names that are blocked (routed to localhost)

3) Run `cat /etc/pf.anchors/org.eyebeam` to see the list of IP addresses/ranges that are blocked.

4) Look at the requests that are not loading on GitHub (Chrome network monitor works well for this) and see what domains/IP addresses are failing

5) Match up to the lists in steps 2/3 and go from there

Hope you're able to figure it out!
