### ISSUE TITLE
SELF CONTROL PERMANENTLY BLOCK WEBSITES

### ISSUE THREAD

**Issue by eva-katerina** [SelfControlApp/selfcontrol#556]
SELF CONTROL APP HAS PERMANENTLY BLOCKED THE WEBSITES.

I tried all the tricks to make the websites work. I uninstalled and installed the Self Control app many times. I changed the date and time (1 day in advance to confuse the calendar of the app) but nothing.

Today I contacted Apple Customer support and I talked with 4 different representatives, including one senior. They all tried to help me but still the websites are permanently blocked. The representatives guided me to clear different sections from the Library (caches, safari extensions etc.). I completely reinstalled the mac software. I opened a completely new account as a new user and still nothing.

The websites are still blocked on both Safari and Google Chrome. In the end the Senior Apple representative told me that this is out of Apple's control and they cannot do anything more to help me and the only solution is to contact you.

It seems that this is an outside block, perhaps block of my IP address.
I NEED YOUR HELP IMMEDIATELY!! YOU HAVE TO STOP THIS BLOCK SO I CAN USE THOSE WEBSITES AGAIN

**Comment by cstigler** [comment]
Hi Katerina, I appreciate that you're concerned about accessing websites on your blocklist, and I replied to the email you sent separately. Your problems may or may not be caused by SelfControl, it's a bit hard to say.

Please remember that this is a free product, provided without warranty or promise of support. Nobody's getting paid to work on this. It's just me, with a full-time job and a life, volunteering some of my time to help you (and anyone else who has questions/concerns). Empathy would be appreciated :)
