### ISSUE TITLE
Editing the hosts file permitted

### ISSUE THREAD

**Issue by ksmithbaylor** [SelfControlApp/selfcontrol#57]
For many more computer-savvy users, it is well known that the hosts file is what blocks and routes IP requests. If I have a site blocked and I go in and directly edit the hosts file, I can immediately go to that site. 

What if the app, upon starting the blocking, also started a background script that saved the contents of the hosts file to a random place on the user's disk (preferably a different place each time, using a hidden file), watched the hosts file for modifications, and then overwrote any changes the user makes to the hosts file when they attempt to save it? It would be nice if the script had a different name each time, too, for those who know to look in the activity monitor or run a ps -ef.

This may be overkill for most users, but I know that for me personally I find the usefulness of selfcontrol limited because I happen to know how to get around it this way.

**Comment by broskees** [comment]
Hi Guys, I'm curious about this. I often use vagrant boxes and such for web development (my job) and they usually make modifications to the host file themselves. If i use this app, will it try an overwrite the hosts file after vagrant updates it?

**Comment by cstigler** [comment]
@broskees I'd guess it won't affect anything in that case, because SelfControl just looks to see if the hosts file _does not_ contain the SelfControl block and re-adds it if so. As long as Vagrant etc aren't removing the SelfControl block, I don't think anything would happen.

That said IDK how they'd really interact, so I'd recommend just running a short test block and seeing what happens.

(closing this issue because it seems apparent we're not changing any behavior here anytime in the foreseeable future)

**Comment by AlexTelea** [comment]
Yep, but what about deleting the SelfControl app (including killing all processes) AND in the same time editing /etc/hosts? Who would take care next that /etc/hosts wasn't tampered with?
