### ISSUE TITLE
Timer extensions from previous blocks are applied at the start of a new block.

### ISSUE THREAD

**Issue by dtrts** [SelfControlApp/selfcontrol#578]
I will detail here what just happened to me. The length of the blocks prevented me for doing any more testing so apologies in advance for the lack of different data. 

1. I updated the version and started a 24hr block 
2. Using the Extend block timer I added 100hrs, and 15mins x 3 
*one week later*
3. Using the standard dialog box I started a new block. The timer said the block would last 24hrs. I did not move the slider. I only opened the app and clicked 'Start Block' 
4. A new block has begun with 124hr 45min 

I had updated the macOS version between the blocks, so there were a couple of restarts between. 

Thanks for reading.

**Comment by erichkauffman** [comment]
I've had the same issue, except I have not updated my macOS version, nor have I restarted my computer.

**Comment by marshallhopkins** [comment]
My previous extension was for 400 hrs. Suprise!

**Comment by cstigler** [comment]
Thanks for the report,  @dtrts! This is indeed a bug. The ideal fix is for timer extensions to not impact new blocks at all, but getting that working is pending a big refactor I'm working on, so until then I put in a makeshift fix.

Fixed so that 1) the Start window shows an accurate report of the block duration you're about to start, and 2) it will never start for longer than 24 hours or the MaxBlockLength

Upgrade to 2.3.1!
