### ISSUE TITLE
Some blocks bypassed with DNS over HTTPS turned on

### ISSUE THREAD

**Issue by gohara92** [SelfControlApp/selfcontrol#584]
Some of my blocks are circumvented in Firefox with DNS over HTTPS turned on.
Strangely enough, one of these blocks (theguardian.com) which was previously circumvented now isn't after putting the full url (https://www.theguardian.com/uk) into the blacklist.

What's going on here? Is this something that's fixable?

**Comment by cstigler** [comment]
@gohara92 so unfortunately, DoH bypasses one of our two blocking mechanisms. We block by DNS (using the `/etc/hosts` file), and then by IP address using the `pf` firewall. The `/etc/hosts` file isn't respected when using DoH, unfortunately, so that's one less layer of redundancy for blocking (and more likely that sites will slip through). I'm not sure that there's a way to fix it, at least not without totally changing the way we block sites...

**Comment by gohara92** [comment]
Thanks for the response Charlie - I'll turn DoH off for now and hopefully forget it exists.
