### ISSUE TITLE
Collateral damage blocking sites

### ISSUE THREAD

**Issue by matthew-a-dunlap** [SelfControlApp/selfcontrol#597]
I noticed recently that when I'd run SelfControl, djangoproject.com would be blocked even though it was not in my list. Turns out when I was blocking reverb.com the other site would be blocked as well.

I think this is because both are hosted by Fastly under 151.101.x.x and SelfControl ends up taking one down with the other. Before this point I had thought SelfControl only edited the hosts file but doing its hosts change manually did not cause this issue.

Anyways, I'm assuming this is a known issue or an expected side-effect of trying to successfully block sites, but I thought I'd at least post it here so if anyone else has similar issues they may see it. I didn't really have time to dig into the source code and try to understand all the places SelfControl touches

**Comment by matthew-a-dunlap** [comment]
Ah, if I turn off "block common subdomains" my issue is resolved. From reading another issue, I take it that's because by default SelfControl also uses `pf` and "block common subdomains" turns it off? Anyways, I hope someone finds this info quicker than I did ;)

**Comment by oeverton86** [comment]
It blocked github.com! 😱
I've used SelfControl for 2 days and it was working as I expected, blocking the domains from the blacklist (time to rename it to block-list, no?), Whatsapp, and social networks. But today it simply blocked the whole thing, including Github, Slack and Stackoverflow - how is a programmer supposed to work without Stackoverflow (kidding, but very seriously)?

Can't say for sure if this is an unexpected result or if I misunderstood the app purpose but IMHO, despite all the distractions that the Internet throws at our faces, most of the people who currently works on a computer need to do this in a connected way.

Please, don't receive this as an distructive yelling, I deeply appreciate the work you've made so far. Maybe it is time for me to learn about programming for the Apple platform so I could effectively help.

Tks

**Comment by yangcht** [comment]
Hope SelfControl can adopt some mechanism to identify the clients. For example, leaving Whatsapp app working but block facebook.com on browsers. Currently, if you block the whole domain, Whatsapp will be blocked too. 

As a workaround, I am using LittleSnitch to do the trick. But it's not a "SelfControl" style of blocking, it's more like soft block. But LittleSnitch can block communication per client.

**Comment by cstigler** [comment]
Hi all, thanks for the feedback. Since this kind of issue ("this website is blocked even though it shouldn't have been") is very common and it's been nearly impossible for me to keep up with our GItHub Issues, I started a [new issue](https://github.com/SelfControlApp/selfcontrol/issues/680) to consolidate all of these kinds of problems in one place.

**If you're still having issues with sites being blocked when they shouldn't be, [please go to this issue and follow the instructions there](https://github.com/SelfControlApp/selfcontrol/issues/680).** It will guide you through some debugging steps, then request some information from you in a standardized format if the debugging didn't work. The idea is that I can get a sense of which websites are most problematic and what the causes are, to help focus future efforts.

Thanks for the help and hope things have cleared up since these comments were left.
