### ISSUE TITLE
Doesn't block reddit

### ISSUE THREAD

**Issue by cosmicprank** [SelfControlApp/selfcontrol#599]
Simply isn't blocking reddit. Don't know what to do or change. Blocks every other site just fine.

**Comment by benmobbs** [comment]
Have you made sure you're also blocking any subdomains, CDN. Try checking the option "block common subdomains".

**Comment by ilMagnifico** [comment]
Hi,
I had the same problem, I resolved trying to add multiple combination of the website such as:

> https://www.twitch.tv
> http://www.twitch.tv
> www.twitch.tv

**Comment by james-tindal** [comment]
You need to clear the cache. Hold shift and refresh.

**Comment by cstigler** [comment]
Hi all, thanks for the feedback. Since this kind of issue ("this website isn't blocked even though it should be") is very common and it's been nearly impossible for me to keep up with our GItHub Issues, I started a [new issue](https://github.com/SelfControlApp/selfcontrol/issues/680) to consolidate all of these kinds of problems in one place.

**If you're still having issues with sites not being blocked when they should be, [please go to this issue and follow the instructions there](https://github.com/SelfControlApp/selfcontrol/issues/680).** It will guide you through some debugging steps, then request some information from you in a standardized format if the debugging didn't work. The idea is that I can get a sense of which websites are most problematic and what the causes are, to help focus future efforts.

Thanks for the help and hope things have cleared up since these comments were left.
