### ISSUE TITLE
Can be stopped by changing local date/time

### ISSUE THREAD

**Issue by SeabassHeyneman** [SelfControlApp/selfcontrol#601]
I can stop a block by going to Date and changing the date to a time in the future.

Can I fork this and point it to an external time service?

Thank you!

**Comment by cstigler** [comment]
Hi @SeabassHeyneman thanks for the note and for offering to help! Yes, that is a problem and has been for many years.

Let's move to #28 for the full discussion, including a patch that somebody wrote a long time ago. The problem is it takes a lot of work, and then testing, to get that to something mergeable. And I'd want to make sure that if the external time service fails (ex: server is down), it falls back to local time instead of leaving the user stranded. There was a good bit of work to get that going, nobody ever did it, and so it's still sitting there! But your help very welcome and I'm happy to help guide you if you do start updating that PR or putting together a new one. (Or obviously you're always welcome to fork and _not_ contribute it back - but wouldn't it be more fun if everybody had the same functionality? :)

One odd sidenote: I have a huge refactor going right now which I hope to merge in the coming weeks. If you do start working on this in the next month or so, please base it off the end-date branch so it's not a nightmare merge 😱
