### ISSUE TITLE
Edit blacklist is not working

### ISSUE THREAD

**Issue by rislam** [SelfControlApp/selfcontrol#604]
<img width="418" alt="selfcontrol" src="https://user-images.githubusercontent.com/1030787/77278612-0ba07b80-6c7d-11ea-939c-830a102a1d60.png">

Current version of app: Version 2.3.2 (2.3.2)
Operating System: macOS high Sierra 10.13.6 (17G11023)

**Comment by rislam** [comment]
Version 2.3.1 (2.3.1) is working fine.

**Comment by cstigler** [comment]
@rislam huh, weird! thanks for the report and I'll try to take a look at it when I can. I can't think why it's broken for now you but not for me.

The only commit between 2.3.1 and 2.3.2 was @jiayi-zhou's very kindly contributed Dark Mode fix. But I see he also pointed out that there's a problem with our constraints which causes them to behave non-deterministically, and contributed a separate fix for that (#590) which I meant to merge but didn't (have a terribly huge branch I've been meaning to merge for a while and was scared of the rebase). Will make sure that gets merged sooner rather than later and hopefully will fix

**Comment by leost1** [comment]
I have the same issue with 2.3.2, is there any way I can download the 2.3.1 if it's currently working? 
Thanks for your help !

**Comment by rislam** [comment]
Try this [one](http://downloads.selfcontrolapp.com/SelfControl-2.3.1.zip)

**Comment by leost1** [comment]
Thanks, it works.

**Comment by cstigler** [comment]
I just merged the fix mentioned above, and confirmed it fixes the issue, so closing now. The next SelfControl release will have the fix (or if you're technical, you can recompile before then!). There'll be a good bit of testing before I push the new version, so it will probably be a few weeks before I get around to pushing it out...
