### ISSUE TITLE
App blocks gitlabs static asset server

### ISSUE THREAD

**Issue by reedox** [SelfControlApp/selfcontrol#608]
Hey,

I've run into an issue where I can't use gitlab while SelfControl is enabled as the CSS/JS is blocked.

The subdomain blocked is: https://assets.gitlab-static.net/assets/... net::ERR_CONNECTION_REFUSED

I looked over the blacklist and this domain isn't listed anywhere, I've also unchecked "Block common subdomains" and that doesn't make a difference.

OSX: 10.15.4
SelfControl: 2.3.2

**Comment by rvanbaalen** [comment]
I second this. I'm trying to get work done using SelfControl but now I can't access crucial parts of my workflow haha.

**Comment by cstigler** [comment]
Hi all, thanks for the feedback. Since this kind of issue ("this website is blocked even though it shouldn't have been") is very common and it's been nearly impossible for me to keep up with our GItHub Issues, I started a [new issue](https://github.com/SelfControlApp/selfcontrol/issues/681) to consolidate all of these kinds of problems in one place.

**I've added this on your behalf to [that meta-issue](https://github.com/SelfControlApp/selfcontrol/issues/681).** The relevant debugging info, if you have it to add to that thread, is what _else_ is on your blocklist. Almost certainly, the issue is something else on your list that shares servers/networking with the problematic site.

Thanks for the help and hope things have cleared up since these comments were left.
