### ISSUE TITLE
Feature: Keep blocklist visible

### ISSUE THREAD

**Issue by maurelian** [SelfControlApp/selfcontrol#614]
First, I love selfcontrol, it's simple, non-intrusive, and it works. I appreciate it so much, thank you! 🙏 

**Motivation:** Usually I just want to block myself from checking twitter/social. But sometimes I setup a more intense blocklist, including email and slack. The problem is when I come back later, and just want to block twitter/social, but forget I have the more extensive blocklist setup.

**Feature request:** It would rock if the blocklist was part of the primary UI, so that it would be visible whenever you open Selfcontrol. It could simply be docked below the slider. 

I have never worked on a mac desktop app... but it seems like this feature might be fairly straightforward, so with a bit of direction I think I might be able to submit a PR.

**Comment by cstigler** [comment]
Love this idea @maurelian! I'm not sure from a design perspective I'm into having the entire scrollable list always visible (feels a little messy), but maybe we could show a "teaser" of what and how much you're blocking? (could also say "Blocking" vs "Allowing" as a reminder of whether it's a blacklist or whitelist block) Like this little mockup I just threw together...
![Screen Shot 2020-05-15 at 12 59 02 PM](https://user-images.githubusercontent.com/67932/82091349-07f10a00-96ac-11ea-9365-384a8ef11fc1.png)

If you're interested, would be very happy to point you the right direction in putting together a PR! Otherwise, I'll add it to my backlog :)

**Comment by maurelian** [comment]
> If you're interested, would be very happy to point you the right direction in putting together a PR! Otherwise, I'll add it to my backlog :)

I mean, it's likely a 1 to 2 months kind of thing for me even, but I am interested in learning how to do this and improving the tool. 

To keep it light for you, could you just point to the relevant files, and a documentation or tutorials for the relevant stack?

**Comment by cstigler** [comment]
Yep!

I won't claim to know the best documentation/tutorials, but the stack you're looking for is Objective-C / Cocoa for macOS development. I suspect there won't be a ton of recent tuts since so much of the Apple dev ecosystem is focused on Swift / iOS development these days...

I think implementing the mockup above should actually be a pretty small changeset:

1. Generate the "Blocking youtube.com, facebook.com, and 47 others" string. I'd probably just generate this in `AppController.m` (which controls the Start window). The blocklist is stored in our secured settings system, you can access as `[settings_ valueForKey: @"Blocklist"]`.
2. Make sure that string is properly localizable - presumably you don't know the actual translations into all the languages, but it should at least be translation-ready so folks can add them.
2. Add an `NSLabel` text box in Interface Builder (the start screen is in `MainMenu.xib`, and hook it up to update based on the generated string. I think the easiest way to make sure it stays up to date is to update it in the `refreshUserInterface` method in `AppController.m`
3. Move a few existing things around in the Interface Builder file - move the time label up above the slider, and the "Edit Blocklist" button to the far right. If I recall correctly, these are all constraints-based these days, so you'll need to make constraints that position them properly.

Hope that helps! Let me know if you need more info.

**Comment by moltar** [comment]
Another use case, which is a super edge case, but figured I'd mention it.

I just re-installed the app after having it uninstalled for a long time.

Just clicked "Start" to see if everything works. And it did. But now Google is blocked. I don't know if it is in the list, or maybe the app picked up my old list. I basically have no way of knowing for an hour what is blocked :)

**Comment by maurelian** [comment]
The truth is, I'm just not going to get around to this. But I do wish I could sponsor you to compensate you a bit for the value this too brings me.

**Comment by cstigler** [comment]
Good news: I just built this and committed it! See [this commit](https://github.com/SelfControlApp/selfcontrol/commit/612c0d46cafa70184b27187b1be67197c9f45335) for the change.

It'll be in the next release, 4.0, which will probably come out in a few weeks (plus or minus some more weeks). Lots of other good features in there too. I'll probably run a small beta test group for a week or so to make sure it doesn't break anything on a wider array of systems, since I'm changing a lot. Let me know if you want to join that :)

**Comment by maurelian** [comment]
Awesome thanks so much! Yes, I'd be happy to help beta test. :)

**Comment by cstigler** [comment]
@maurelian awesome - took me a while longer than expected (doesn't it always), but the 4.0 alpha is ready to test now.

**To get started alpha testing, [go to this link and fill out the intake form](https://forms.gle/4EaMFzEGK3zXKzfw7) (takes 2 min or less). After you submit the form, you'll get a link to download the new alpha version.**

Thanks for the help testing and let me know how it goes!
