### ISSUE TITLE
Changes my desktop background

### ISSUE THREAD

**Issue by luisaenria** [SelfControlApp/selfcontrol#616]
Hi! Since I updated to the latest version SelfControl seems to change my desktop background automatically to "Cheater!". While I appreciate the extra motivation, I am not sure what causes it to do it (I haven't tried to remove the block) and it's getting annoying to have to keep changing my background. How do I disable this feature? Thanks!

**Comment by cstigler** [comment]
Oh no! Sorry you're having issues @luisaenria.

The bad news is: I don't have an immediate fix, because I'm not sure exactly what's going wrong yet (you're the second person to report this problem). The good news is: if you're able to spend the time with me to help debug it, you'll be helping solve this issue for many other people too!

If you're up for it, could you please send me an email to charlie+sc616@charliestigler.com with the following info, and we can work together to try to track the bug down?

1. What version of macOS are you running? Any special configuration or circumstances you're aware of?

2. How many times has this happened to you? Does it happen every time a block ends, or just sometimes?

3. Did the block end on schedule (as normal), or did you have to use the "Stuck? Stop block manually" button to clear it?

4. Please open up Terminal and run the following command and copy/paste the entire output back to me (and let me know whether a block was / was not running when you ran the command): `sudo /Applications/SelfControl.app/Contents/MacOS/org.eyebeam.SelfControl $(id -u $(whoami)) --print-settings`

Thank you for the help!

**Comment by cstigler** [comment]
An update on this: I have a beta version of the app which should fix this issue. @luisaenria would you be able to give it a try? Steps are...

1. Wait until your current block is finished. 

2. Delete your SelfControl application, and change your desktop background back to your usual (i.e. away from our "Cheater" background).

3. Download the new beta version of SelfControl from [this special link](https://downloads.selfcontrolapp.com/SelfControl-3.0.1-beta.zip), and install it on your computer.

4. Start a new (short) block, change your background back to usual (if it's reset again), and wait for it to finish.

5. Wait an extra 1 minute, quit SelfControl, then reopen it again.

6. Check whether your background has changed.

**Comment by cstigler** [comment]
The tentative fix for this has been released as version 3.0.1. If anybody reading this is having this problem, please first try updating to version 3.0.1 and starting your next block on the latest version. If you're still having issues, you can reopen this issue or start a new one.
