### ISSUE TITLE
Blacklist websites no longer work

### ISSUE THREAD

**Issue by hendrix103** [SelfControlApp/selfcontrol#638]
Hi, since i update my Mac to Catalina (new version), it seems, that i can't block anymore website with SelfControl. I copy past the link with or without "https", "www". But i can still access the website I tried to block. I think it is due to the app "Temps d'écran" (don't know the name in english) from Apple that appears with Catalina. 
Do you know a way to fix the bug ?
Thank you !

**Comment by jazrak** [comment]
By 'new version', are you sure you're not referring to Big Sur (not Catalina)?

**Comment by cstigler** [comment]
Hi @hendrix103, I am not familiar with any issues on Catalina unfortunately (there are active issues with Big Sur).

if you're still having issues, I'd suggest:

1. Make sure that you're on the latest version of SelfControl (3.0.2) and that you're on Catalina, _not_ Big Sur.

2. Make sure you're not using a VPN/proxy, or using DNS Over HTTPS on Firefox.

3. Try starting the block, clearing your browser cache, closing your browser, and opening it again

Hope it works out! Unfortunately I can't troubleshoot individual system-level block failures since there are just too many variables.

**Comment by hendrix103** [comment]
thanks for all the answers. I'm using Catalina version 10.15.6
I realised that I can no longer block using the Terminal also through "sudo nano /etc/hosts". So it seems not being a problem from the app. And it appears by updating my Mac.
