### ISSUE TITLE
SelfControl stuck on finishing

### ISSUE THREAD

**Issue by ElizabethBurgess** [SelfControlApp/selfcontrol#642]
My SelfControl is stuck on finishing. I put the application in my trash and emptied it. It still ran. I re-downloaded it. It's still stuck on finishing. 

I'm getting an error message that says "stop block manually."
<img width="247" alt="Screenshot 2020-09-30 at 14 02 18" src="https://user-images.githubusercontent.com/45107127/94688580-b4631e00-0325-11eb-87ab-058c98a55851.png">

When I do this it prompts me for my password and then another message comes up saying " Success!, The block was cleared successfully.  You can find the log file, named SelfControl-Killer.log, in your Documents folder. If you're still having issues, please check out the SelfControl FAQ on GitHub."

Needless to say, the block has not stopped. Send help.

**Comment by bwray** [comment]
Sometimes when that happens to me I'll quit the app, only to open it up to see the same "finishing" message you posted an image of, then I manually stop it again and success for real.

**Comment by ElizabethBurgess** [comment]
That's not working for me unfortunately

**Comment by ElizabethBurgess** [comment]
I've been blocked for about a week now

**Comment by cstigler** [comment]
Hi @ElizabethBurgess, sorry to hear you've been having issues with SelfControl - that sounds frustrating. Just to confirm, is the issue that the SelfControl app still _says_ the block is running, or that the sites are actually not accessible?

My first suggestion if you haven't tried it is simply restarting your computer. I'd open SelfControl one more time, click to clear your block manually again, and then clear your browser cache and restart your computer.

If you're still having issues, send me an email at charlie+sc642@charliestigler.com and I can help you figure it out. Please attach the `SelfControl-Killer.log` file which should be in your Documents folder, and include the following info:

- SelfControl version (go to SelfControl --> About) in the app
- macOS version
- whether you're using a VPN or proxy (ex, on a corporate or school machine)
- any other special conditions that might apply to you, or things that have changed recently

**Comment by kmh1000** [comment]
I've got this same problem. Were you able to figure this out? I've had this problem in the past and followed the directions  posted in #486 but that is not working now :(  This usually happens when the countdown ends while I'm using VPN.

**Comment by cstigler** [comment]
Hi @kmh1000, SelfControl is not compatible with VPNs, and the VPN is almost certainly the issue in your case. You'll need to make sure the VPN is off at least while starting SelfControl and while the block is ending.

If you haven't managed to get your internet access back, email me at charlie+sc642@charliestigler.com and I can help you fix it.

**Comment by pandorasbox2340** [comment]
So when is Self Control gonna be an app on my phone.   Growing tired of
waiting.

**Comment by abhishektyagi** [comment]
So none of it work. Deleting SelfControl entries from `/etc/hosts` file worked.

**Comment by pandorasbox2340** [comment]
Let’s get togetherWe’re hosting a new event, and we’d love to see you there. Join us for Belly of the Beast Free Virtual Screening and In Person Screening, May 6, 2021 at 6:45 PM.Register soon, because it&#x27;s Airing this Thursday. We hope you’re able to join us!1) Come in Personor2) Watch Online ＴＨＩＳ ＷＥＥＫ ＩＳ ＴＨＥ ＷＥＥＫ&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;𝙱𝙴𝙻𝙻𝚈 𝙾𝙵 𝚃𝙷𝙴 𝙱𝙴𝙰𝚂𝚃&quot;If you can&#x27;t make it in person, sign up on Eventbrite (https://clicks.eventbrite.com/f/a/AZLCl9cTe6Y3jsijUVpN5A~~/AAQxAQA~/RgRidHyiP0Q2aHR0cHM6Ly93d3cuZXZlbnRicml0ZS5jb20vLi4uL2JlbGx5LW9mLXRoZS1iZWFzdC1mcmVlVwNzcGNCCmCMoveRYEhmlNtSQXJlcGx5K2FybTRqdmxycGtwZnJ2czZzcjZncmtuNTVlZjJuZXZibmhoY3UzenBuZUByZXBseS5naXRodWIuY29tWAQAAAAE...) and a virtual link will be sent to your email with the activation code once you register (also free of charge).&nbsp;&nbsp;The link will be active for 24 hours.“...Erika Cohn’s documentary “Belly of the Beast,” which depicts the fight to ban non-consensual sterilizations performed on female prisoners in California, is at once a thrilling legal drama and heartbreaking depiction of devastating human rights violations that you can’t imagine happening in the 21st century...” ~ The Los Angeles Times Film Website: https://clicks.eventbrite.com/f/a/HmITP_kcdiyZdBhjAasUXw~~/AAQxAQA~/RgRidHyiP0QkaHR0cHM6Ly93d3cuYmVsbHlvZnRoZWJlYXN0ZmlsbS5jb20vVwNzcGNCCmCMoveRYEhmlNtSQXJlcGx5K2FybTRqdmxycGtwZnJ2czZzcjZncmtuNTVlZjJuZXZibmhoY3UzenBuZUByZXBseS5naXRodWIuY29tWAQAAAAE Facebook: https://clicks.eventbrite.com/f/a/qUz3g7FLjxY4NIUZRZXpyw~~/AAQxAQA~/RgRidHyiP0QsaHR0cHM6Ly93d3cuZmFjZWJvb2suY29tL2JlbGx5b2Z0aGViZWFzdGZpbG1XA3NwY0IKYIyi95FgSGaU21JBcmVwbHkrYXJtNGp2bHJwa3BmcnZzNnNyNmdya241NWVmMm5ldmJuaGhjdTN6cG5lQHJlcGx5LmdpdGh1Yi5jb21YBAAAAAQ~ Twitter: https://clicks.eventbrite.com/f/a/uUDBrisnpzqpFhnqAcWo8g~~/AAQxAQA~/RgRidHyiP0QcaHR0cHM6Ly90d2l0dGVyLmNvbS9ib3RiZmlsbVcDc3BjQgpgjKL3kWBIZpTbUkFyZXBseSthcm00anZscnBrcGZydnM2c3I2Z3JrbjU1ZWYybmV2Ym5oaGN1M3pwbmVAcmVwbHkuZ2l0aHViLmNvbVgEAAAABA~~ Instagram: instagram.com/bellyofthebeastfilm/ Hashtag: #BellyoftheBeast, #BOTBfilm



Featured Events:

Belly of the Beast Free Virtual Screening and In Person Viewing | Historic Palace Theatre | 2021-05-06T22:45:00Z
https://clicks.eventbrite.com/f/a/4aOAFJjz8agzE0WHGA2n9w~~/AAQxAQA~/RgRidHyiP0QaaHR0cHM6Ly93d3cuZXZlbnRicml0ZS5jb21XA3NwY0IKYIyi95FgSGaU21JBcmVwbHkrYXJtNGp2bHJwa3BmcnZzNnNyNmdya241NWVmMm5ldmJuaGhjdTN6cG5lQHJlcGx5LmdpdGh1Yi5jb21YBAAAAAQ~






Unsubscribe: https://www.eventbrite.com/organizations/missive/activity/unsubscribe/?p=ABIdvVtnGuGGPrluTBOeO_8MbPpyMGBHOoZ4blEcchqy1wMZhXZjcS6w7BAfIBRuICJVsD0LPIbZGJ4uNwPIP__K_ohQmNSDiOt_xy9sYehFKuWKfmkrFkhEZ8FhBvaMKbL5xsX0Mge3rsSxtswRJzOPxnIuW0YiStuGNg71_exSj-6fWUZdHDkLvVAHC6h0JMdgeWCu7BBN1RK4qk692Tj-__gsmzpy3ORPkZyhpC5J9jF5Om7PEWwtP4BNFCAtrtHmyNvQI1cFk3wJIRxMw5MjFAvn-Tq8AIK6updr9JJ52qvFu7SpwxojxAUIFD59BDLGeh3fycll&c=787768&co=216110936

**Comment by cstigler** [comment]
Hi @pandorasbox2340 could you please not post unrelated event invites on our bug tracker?

**Comment by pandorasbox2340** [comment]
It’s an automated list.  You can always unsubscribe, like the rest of
America does for inconvenient truths.
