### ISSUE TITLE
What files other than /etc/hosts does this touch?

### ISSUE THREAD

**Issue by andrewkouri** [SelfControlApp/selfcontrol#648]
I put this on my work laptop, and we use OpenVPN. Not sure if that interferes with the program.

Unfortunately I can no longer connect to the internet (at all) on this laptop. I am trying to fix it, but need to know what other system files this may have touched so I can revert them.

Interestingly, it seems as though my DNS is messed up too, not just the hosts file.

**Comment by andrewkouri** [comment]
Update - 2 hours in to debugging this. I've managed to disable PF via `pfctl -d` and reset my /etc/hosts back to default, but still no connection at all.

**Comment by cstigler** [comment]
Hi @andrewkouri, as it sounds like you've figured out by now, SelfControl blocks via two methods:

1. the `/etc/hosts` file
2. the `pf` firewall

It also installs itself as a `launchd` daemon, which doesn't affect networking in itself, but it will attempt to re-add the block if it's been removed from the `/etc/hosts` file. Those are the only system files SC modifies (it stores settings in a couple different files, but those are SC-specific files that you can safely ignore).

If you've already reset `/etc/hosts` and `pf`, and you can't connect to anything (it's not specific to your blocklist), I'd guess your issue is probably not SelfControl-related. Some partial VPNs do modify the hosts file and reset them back, which can interact poorly with SelfControl (see the FAQ for more details on that). But if you're sure the hosts file and `pf` are clear, and you've cleared your DNS cache / restarted your computer, I'm not sure what else to suggest.

Feel free to email me at charlie+sc648@charliestigler.com if you want further help.

**Comment by akouri-dd** [comment]
Thanks Charlie - that's really kind of you to respond. I read through all the code, and gathered just as much. Ultimately what ended up fixing it for me was to remove my wifi _and_ ethernet interfaces and reinstall them... go figure.

**Comment by cstigler** [comment]
Glad you got it working in the end! :)
