### ISSUE TITLE
How to manually create a blocklist file?

### ISSUE THREAD

**Issue by theonlygusti** [SelfControlApp/selfcontrol#654]

**Comment by cstigler** [comment]
There's no official/supported way to do this, but it's just a plist file so if you're technically inclined you can figure it out. Here's the source code showing how they're generated: https://github.com/SelfControlApp/selfcontrol/blob/b1264dd2b53805a99bc07e87085cba3ea82f0080/AppController.m#L887

**Comment by pandorasbox2340** [comment]
Thanks.   So Much.


What a fiery day!  Eye of the Tiger!

**Comment by pandorasbox2340** [comment]
Let’s get togetherWe’re hosting a new event, and we’d love to see you there. Join us for Belly of the Beast Free Virtual Screening and In Person Screening, May 6, 2021 at 6:45 PM.Register soon, because it&#x27;s Airing this Thursday. We hope you’re able to join us!1) Come in Personor2) Watch Online ＴＨＩＳ ＷＥＥＫ ＩＳ ＴＨＥ ＷＥＥＫ&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;𝙱𝙴𝙻𝙻𝚈 𝙾𝙵 𝚃𝙷𝙴 𝙱𝙴𝙰𝚂𝚃&quot;If you can&#x27;t make it in person, sign up on Eventbrite (https://clicks.eventbrite.com/f/a/tto316TLW8zL7EGprJxNHg~~/AAQxAQA~/RgRidHyiP0Q2aHR0cHM6Ly93d3cuZXZlbnRicml0ZS5jb20vLi4uL2JlbGx5LW9mLXRoZS1iZWFzdC1mcmVlVwNzcGNCCmCMoveRYEhmtdtSQXJlcGx5K2FybTRqdml6YzZqZXBzY2l4ZHB2Y2h2NTJtd3ZwZXZibmhoY3p0M2ptdUByZXBseS5naXRodWIuY29tWAQAAAAE...) and a virtual link will be sent to your email with the activation code once you register (also free of charge).&nbsp;&nbsp;The link will be active for 24 hours.“...Erika Cohn’s documentary “Belly of the Beast,” which depicts the fight to ban non-consensual sterilizations performed on female prisoners in California, is at once a thrilling legal drama and heartbreaking depiction of devastating human rights violations that you can’t imagine happening in the 21st century...” ~ The Los Angeles Times Film Website: https://clicks.eventbrite.com/f/a/sUDei6Ss6z3_pJw6GichYQ~~/AAQxAQA~/RgRidHyiP0QkaHR0cHM6Ly93d3cuYmVsbHlvZnRoZWJlYXN0ZmlsbS5jb20vVwNzcGNCCmCMoveRYEhmtdtSQXJlcGx5K2FybTRqdml6YzZqZXBzY2l4ZHB2Y2h2NTJtd3ZwZXZibmhoY3p0M2ptdUByZXBseS5naXRodWIuY29tWAQAAAAE Facebook: https://clicks.eventbrite.com/f/a/xhbiW-56Q3BqDisWotrH3A~~/AAQxAQA~/RgRidHyiP0QsaHR0cHM6Ly93d3cuZmFjZWJvb2suY29tL2JlbGx5b2Z0aGViZWFzdGZpbG1XA3NwY0IKYIyi95FgSGa121JBcmVwbHkrYXJtNGp2aXpjNmplcHNjaXhkcHZjaHY1Mm13dnBldmJuaGhjenQzam11QHJlcGx5LmdpdGh1Yi5jb21YBAAAAAQ~ Twitter: https://clicks.eventbrite.com/f/a/39B9SyveFQUind8NWATyrA~~/AAQxAQA~/RgRidHyiP0QcaHR0cHM6Ly90d2l0dGVyLmNvbS9ib3RiZmlsbVcDc3BjQgpgjKL3kWBIZrXbUkFyZXBseSthcm00anZpemM2amVwc2NpeGRwdmNodjUybXd2cGV2Ym5oaGN6dDNqbXVAcmVwbHkuZ2l0aHViLmNvbVgEAAAABA~~ Instagram: instagram.com/bellyofthebeastfilm/ Hashtag: #BellyoftheBeast, #BOTBfilm



Featured Events:

Belly of the Beast Free Virtual Screening and In Person Viewing | Historic Palace Theatre | 2021-05-06T22:45:00Z
https://clicks.eventbrite.com/f/a/-qJFCJ5BBbX7UmxDI17szQ~~/AAQxAQA~/RgRidHyiP0QaaHR0cHM6Ly93d3cuZXZlbnRicml0ZS5jb21XA3NwY0IKYIyi95FgSGa121JBcmVwbHkrYXJtNGp2aXpjNmplcHNjaXhkcHZjaHY1Mm13dnBldmJuaGhjenQzam11QHJlcGx5LmdpdGh1Yi5jb21YBAAAAAQ~






Unsubscribe: https://www.eventbrite.com/organizations/missive/activity/unsubscribe/?p=ABIdvVsKVoafKwHXkHNbFXec2Qb9VHG1s8sJzXsmKzkJGIVB-L0pgkKmZU1GLvf1OGp5lYTn5mP8iDEnAwRU4ed2lxDrKdHNJ2DjtyYF1qn190W_Yzv8a7GP67fkWwD7VIO7syymYB2lcKAzN3flDUuSl2Ob3e4Eq66aFD1eLCwFp1rbsQOghnhWdCJUM91DSvMkShb87Fkib5uJyRGFTrtqE8HnxDZ0JGAaUdsSQyfWVOAQJsaT26iZH8m6i20N7ausZZbheRmUao2UK7UyMBEgASt2ChrVGtSw2QQ99XCPmaOdYq_8OAFYUydnV5szCNdEwnaKGE6l&c=787768&co=216110978
