### ISSUE TITLE
Self Control Hangsup after Password Entry

### ISSUE THREAD

**Issue by cluelesscarter** [SelfControlApp/selfcontrol#688]
# Summary

When I try to start a block, a dialog box appears, "Self Control want to make changes", I enter my password to do this but then the app freezes.

# Background Info

SelfControl version? Version 3.0.3 (3.0.3)
macOS version? Mojhave 10.14.6
Do you use a VPN/proxy, and if so which one? no
Has this _ever_ worked for you on a prior version of SelfControl? If so, when? Self control has worked well for me for 5 years
Any other special system setup we should know about? EndpointSymatec protection installed by IT system (company laptop)

# How Do We Reproduce This Issue?

Try to start a block on a computer that requires a password each time, it should then freeze

# What _Should_ Have Happened?

The block should have started. The box disapears.

# What Actually Happened Instead?

I click 'Ok' and the block greys out, the block does not start and I need to force quit SelfControl.

**Comment by cstigler** [comment]
Hi @cluelesscarter , when you start the block does the "Start" button text change to "Loading"? And are you still able to open the menu bar for SelfControl (e.g. SelfControl, File, Edit, etc), or do you get the rainbow spinner when you try to open them?

SelfControl takes time to start the block, and the time can vary wildly depending on the sites on your blocklist, type of block, network performance, and your particular system configuration, because starting the block requires making a large number of network requests. It sounds to me like your blocks are just taking a lot longer to start than they used to, so you previously didn't notice this effect but now do.

My guess is that it'll eventually start the block if you just wait (walk away for 5 minutes and come back). In terms of making it take less time to start, it could be a result of an antivirus system or network change, but the blocklist is the most likely culprit. I'd try saving your blocklist (File --> Save Blocklist), then making a new blocklist with only one item on it, e.g. a blocklist that only blocks facebook.com. If that starts much faster, then you know it's something with your current blocklist that's causing problems.
