### ISSUE TITLE
Can't add new sites to blocklist after update

### ISSUE THREAD

**Issue by hardianlawi** [SelfControlApp/selfcontrol#719]
# Summary

I updated the app while it is still blocking the websites from the list, but I can't add new websites to the blocklist afterward.

# Background Info

SelfControl version? 4.0 now after update
macOS version? Big Sur 11.6
Do you use a VPN/proxy, and if so which one? No
Has this _ever_ worked for you on a prior version of SelfControl? If so, when? Yes, right before update
Any other special system setup we should know about?

# How Do We Reproduce This Issue?

Not sure since it happens right after I updated the app.

# What _Should_ Have Happened?

I expect I could still add new websites to the blocklist even after updates. Hopefully I don't have to wait until the time is over because I set it to quite long.

# What Actually Happened Instead?

![image](https://user-images.githubusercontent.com/22806872/135750273-94bd7b74-9df9-412b-8155-7d3cea7fc808.png)

**Comment by cstigler** [comment]
Hi @hardianlawi, thanks for the report. It's expected behavior but I can see why it's confusing! We don't recommend upgrading while a block is running because it can cause issues (I know we could make that more clear).

SelfControl 4.0 disables the add to blocklist and extend block timer features on blocks that were started on older versions, because the blocking system has changed and we can't modify older blocks from the newer version.

If you need to add to / extend your block, you can [re-download version 3.0.3 from our website](https://selfcontrolapp.com/) and use that while waiting for your block to finish. Then upgrade after the block is done.

I just took a shot at a better bit of text in-app to explain this, feedback welcome :)

<img width="435" alt="Screen Shot 2021-10-03 at 12 31 54 PM" src="https://user-images.githubusercontent.com/67932/135773819-cb3da237-877b-48ae-859a-40ba21e99559.png">

**Comment by hardianlawi** [comment]
Ah, I see. That's what I suspected. I think it would be great if there is some kind of warning on the update window so users could decide whether to update or not. If I knew this would happen, I wouldn't have updated it immediately. Thanks for the reply though!

**Comment by cstigler** [comment]
The update window does say "Please don't upgrade while a block is running", but I know many of us (including me) have a blind eye for warning text! Anyway, there shouldn't be any issues with downgrading so no harm in going back now.
