### ISSUE TITLE
Countdown not appearing in dock

### ISSUE THREAD

**Issue by mosh76** [SelfControlApp/selfcontrol#724]
# Summary
I updated SelfControl but the countdown is now not appearing in the dock through I've selected it in preferences.

In a sentence or two, what happened?

# Background Info

SelfControl version 4.0.1
Macbook air M1 
macOS Big sur 11.6
No VPN/Proxy
Worked fine on previous version of SelfControl

# How Do We Reproduce This Issue?
Select any time and see if countdown appears in dock

# What _Should_ Have Happened?
Countdown should appear like on older version

# What Actually Happened Instead?
Just see the icon with no countdown

**Comment by cstigler** [comment]
Hi @mosh76, that's annoying! That code didn't really change from 3.x and it's still working for me in 4.0.1, so I'm unfortunately not sure what the issue is.

Two things to try:

1) Could you open Terminal, run `defaults read org.eyebeam.SelfControl BadgeApplicationIcon`, and report back the results?

2) Has this issue happened across multiple blocks? Have you tried restarting your computer, reopening SelfControl, and running a new block? (yes I know this is cliched advice)

**Comment by mosh76** [comment]
Sadly the old restart trick didn't work. I entered that line into Terminal and got: 
2021-10-05 18:15:15.948 defaults[9279:399638] 
The domain/default pair of (org.eyebeam.SelfControl, BadgeApplicationIcon) does not exist

**Comment by cstigler** [comment]
@mosh76 got it, that sounds right.

Here's another idea: technically in more recent versions of macOS, the app icon badging is part of notifications. I wonder if SelfControl doesn't have permission on your system to display badges.

Try opening System Preferences, going to Notifications, then scrolling down the list until you find SelfControl. See if the "Badge app icon" box is unchecked. Even if it is checked, try unchecking and then rechecking that box. Then quit and reopen SelfControl and see if anything's changed...
![Screen Shot 2021-10-06 at 1 53 56 AM](https://user-images.githubusercontent.com/67932/136171715-3e4105cc-dd7d-4405-88b8-f89143b34e79.png)

**Comment by mosh76** [comment]
that's the one - cheers Charlie! (feeling a bit stupid now)

**Comment by cstigler** [comment]
@mosh76 I didn't think of it either at first, so it's a good thing to know for the future!
