### ISSUE TITLE
Option to disable notification?

### ISSUE THREAD

**Issue by mcvmcvmcvmcv** [SelfControlApp/selfcontrol#733]
Hello, I am pretty sure that this hasn't been requested yet, sorry if it is buried somewhere. 

I recently upgraded SelfControl and noticed that, when I finish my session, a notification flies in to let me know. I find this kind of distracting--I would rather *not* know, so that I can continue to not distract myself lol. Of course there is an easy workaround by using Do Not Disturb mode, so this isn't at all dire, but I wonder if it would be possible to make this an option in the application. 

Anyway, thanks so much for this software, it really helps me!

**Comment by cstigler** [comment]
Hey @mcvmcvmcvmcv you can disable this notification on the system level by going to Notification Center (open System Preferences --> Notifications), scrolling down to SelfControl, and changing the alert style to None. Since it can be disabled that way, will probably skip adding a separate setting in SC which seems redundant!
