### ISSUE TITLE
Browsing speed slows when bocking many websites

### ISSUE THREAD

**Issue by akavi1** [SelfControlApp/selfcontrol#818]
I have a block list of 22000 websites. I've found that whenever selfcontrol is running, all of my internet access slows down significantly. Some websites don't even load even though they are not on the block list. Is this expected behavior? Is it possible to block a significantly large number of websites without slowing down access to the rest of the internet?

SelfControl version: 4.0.2
macOS version: 13.0

**Comment by cstigler** [comment]
Hi @akavi1, unfortunately SelfControl is not designed to handle blocklists of that scale - it's really intended for small personal lists, and has never been tested on a list that large.

It wouldn't surprise me if, at that scale, you'd run into various slowdowns. Issue #816 lists one example of a possible cause. It'd be nice to improve performance, but we won't specifically optimize the app for 22K-site blocklists, because that's not a typical use-case.
